name: Flutter Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.10'
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
